export const HARLAND_SAFETY_DATA = {
  125: {
    scorePct: 91,
    scoreWord: "Excellent",
    totalObservations: 17,
    violations: 6,
    safeConditions: 10,
    actionsTaken: 4,
    openActions: 3,
    areasInspected: 9,
    areasTotal: 12,
    lead: "Priya Shah",
    imageOffset: 0,
    areas: [
      "Rear Aisle",
      "Coater Line B",
      "Tensile Test Cell",
      "Main Aisle",
      "East Emergency Exit",
    ],

    observations: [
      {
        category: "Violation",
        catTone: "bad",
        title: "Rear Aisle",
        timeLabel: "6:08 AM",
        body: "Open panel door and worktable obstructing the designated walkway, reducing safe aisle clearance and restricting access.",
        risk: "Medium Risk",
        riskTone: "warn",
        status: "Open",
        stTone: "bad",
      },
      {
        category: "Violation",
        catTone: "bad",
        title: "Main Aisle",
        timeLabel: "5:52 AM",
        body: "Desk, chairs, trash can, floor fan, and loose cable obstructing the designated aisle, reducing safe clearance and creating multiple trip hazards.",
        risk: "High Risk",
        riskTone: "bad",
        status: "In Progress",
        stTone: "warn",
      },
      {
        category: "Violation",
        catTone: "bad",
        title: "Main Aisle",
        timeLabel: "5:41 AM",
        body: "Ladder, chair, and work desks obstructing or encroaching on the designated aisle, reducing safe clearance and restricting passage.",
        risk: "High Risk",
        riskTone: "bad",
        status: "In Progress",
        stTone: "warn",
      },
      {
        category: "Violation",
        catTone: "warn",
        title: "Main Aisle",
        timeLabel: "5:35 AM",
        body: "Ladder positioned within the designated walkway, blocking safe passage and creating an obstruction hazard.",
        risk: "Medium Risk",
        riskTone: "warn",
        status: "Open",
        stTone: "bad",
      },
      {
        category: "Violation",
        catTone: "warn",
        title: "Main Aisle",
        timeLabel: "5:22 AM",
        body: "Two desks and an office chair obstructing or encroaching on the designated walkway, reducing safe aisle clearance and restricting passage.",
        risk: "Low Risk",
        riskTone: "good",
        status: "Open",
        stTone: "bad",
      },
    ],

    trends: {
      obs: { arrow: "up", pct: 15, isGood: true },
      viol: { arrow: "down", pct: 13, isGood: false },
      open: { arrow: "down", pct: 27, isGood: false },
    },
  },

  120: {
    scorePct: 83,
    scoreWord: "Good",
    totalObservations: 18,
    violations: 6,
    safeConditions: 12,
    actionsTaken: 5,
    openActions: 3,
    areasInspected: 8,
    areasTotal: 12,
    lead: "Marcus Webb",
    imageOffset: 1,
    areas: [
      "RDX Assembly Area",
      "Material Staging Lane",
      "Machine Cell 4",
      "North Walkway",
      "Receiving Exit",
    ],
    observations: [
      {
        category: "",
        catTone: "bad",
        title: "Rear Aisle",
        timeLabel: "6:08 AM",
        body: "Aisleway is clear and free of obstructions, providing safe and unrestricted passage through the area.",
        risk: "No Risk",
        riskTone: "good",
        status: "Open",
        stTone: "good",
      },
      {
        category: "Violation",
        catTone: "bad",
        title: "Shipping Area",
        timeLabel: "5:52 AM",
        body: "Shelving cart, fan, floor blower, copier, printer, and equipment obstructing the designated walkway, reducing safe aisle clearance and creating trip hazards.",
        risk: "High Risk",
        riskTone: "bad",
        status: "In Progress",
        stTone: "warn",
      },
      {
        category: "Violation",
        catTone: "bad",
        title: "Main Aisle",
        timeLabel: "5:41 AM",
        body: "Pallet jack positioned within the designated aisle, reducing safe clearance and obstructing passage.",
        risk: "Medium Risk",
        riskTone: "warn",
        status: "In Progress",
        stTone: "warn",
      },
      {
        category: "Violation",
        catTone: "warn",
        title: "Main Aisle",
        timeLabel: "5:35 AM",
        body: "Trolley blocking the aisle and desk encroaching on the marked walkway, reducing safe clearance and restricting passage.",
        risk: "Low Risk",
        riskTone: "good",
        status: "In Progress",
        stTone: "warn",
      },
      {
        category: "Violation",
        catTone: "warn",
        title: "Main Aisle",
        timeLabel: "5:22 AM",
        body: "Pallet jack, desks, and floor fan obstructing the designated aisle, reducing safe clearance and restricting passage.",
        risk: "High Risk",
        riskTone: "bad",
        status: "Open",
        stTone: "bad",
      },
    ],
    trends: {
      obs: { arrow: "up", pct: 12, isGood: true },
      viol: { arrow: "down", pct: 14, isGood: false },
      open: { arrow: "down", pct: 25, isGood: false },
    },
  },

  140: {
    scorePct: 76,
    scoreWord: "Watch",
    totalObservations: 22,
    violations: 9,
    safeConditions: 11,
    actionsTaken: 6,
    openActions: 5,
    areasInspected: 7,
    areasTotal: 12,
    lead: "Anika Iyer",
    imageOffset: 2,
    areas: [
      "Production Cell 1",
      "Conveyor Crossing",
      "Packaging Station",
      "Operator Walkway",
      "South Fire Exit",
    ],
    trends: {
      obs: { arrow: "up", pct: 18, isGood: true },
      viol: { arrow: "up", pct: 9, isGood: false },
      open: { arrow: "up", pct: 11, isGood: false },
    },
  },

  150: {
    scorePct: 89,
    scoreWord: "Good",
    totalObservations: 15,
    violations: 4,
    safeConditions: 11,
    actionsTaken: 4,
    openActions: 2,
    areasInspected: 10,
    areasTotal: 12,
    lead: "Jorge Alvarado",
    imageOffset: 3,
    areas: [
      "Final Assembly Line",
      "Inspection Station",
      "Custom Rig Area",
      "Finished Goods Lane",
      "West Emergency Exit",
    ],
    trends: {
      obs: { arrow: "up", pct: 10, isGood: true },
      viol: { arrow: "down", pct: 18, isGood: true },
      open: { arrow: "down", pct: 20, isGood: true },
    },
  },

  180: {
    scorePct: 81,
    scoreWord: "Watch",
    totalObservations: 20,
    violations: 7,
    safeConditions: 12,
    actionsTaken: 5,
    openActions: 4,
    areasInspected: 7,
    areasTotal: 12,
    lead: "Sophie Tremblay",
    imageOffset: 4,
    areas: [
      "Coating Preparation",
      "Curing Oven Lane",
      "Chemical Storage",
      "Washdown Area",
      "Coating Exit",
    ],
    trends: {
      obs: { arrow: "up", pct: 14, isGood: true },
      viol: { arrow: "up", pct: 6, isGood: false },
      open: { arrow: "down", pct: 8, isGood: true },
    },
  },

  190: {
    scorePct: 87,
    scoreWord: "Good",
    totalObservations: 16,
    violations: 5,
    safeConditions: 11,
    actionsTaken: 4,
    openActions: 2,
    areasInspected: 9,
    areasTotal: 12,
    lead: "Devon Carter",
    imageOffset: 0,
    areas: [
      "Sub-Assembly Cell",
      "Kitting Lane",
      "Component Storage",
      "Material Transfer Path",
      "North Exit",
    ],
    trends: {
      obs: { arrow: "up", pct: 11, isGood: true },
      viol: { arrow: "down", pct: 10, isGood: true },
      open: { arrow: "down", pct: 15, isGood: true },
    },
  },

  220: {
    scorePct: 94,
    scoreWord: "Excellent",
    totalObservations: 13,
    violations: 2,
    safeConditions: 11,
    actionsTaken: 3,
    openActions: 1,
    areasInspected: 11,
    areasTotal: 12,
    lead: "Priya Shah",
    imageOffset: 1,
    areas: [
      "Quality Laboratory",
      "Test Equipment Bay",
      "Sample Storage",
      "Calibration Walkway",
      "Laboratory Exit",
    ],
    trends: {
      obs: { arrow: "up", pct: 7, isGood: true },
      viol: { arrow: "down", pct: 33, isGood: true },
      open: { arrow: "down", pct: 50, isGood: true },
    },
  },

  warehouse: {
    scorePct: 79,
    scoreWord: "Watch",
    totalObservations: 24,
    violations: 8,
    safeConditions: 15,
    actionsTaken: 6,
    openActions: 5,
    areasInspected: 8,
    areasTotal: 14,
    lead: "Carlos Mendoza",
    imageOffset: 2,
    areas: [
      "Inbound Dock",
      "Pallet Storage Lane",
      "Forklift Charging Area",
      "Outbound Staging",
      "Warehouse East Exit",
    ],

    observations: [
      {
        category: "Violation",
        catTone: "bad",
        title: "Rear Aisle",
        timeLabel: "6:08 AM",
        body: "Cardboard panels blocking the aisle and wire decking extending over the marked aisle line, reducing safe clearance and restricting passage.",
        risk: "High Risk",
        riskTone: "bad",
        status: "Open",
        stTone: "bad",
      },
      {
        category: "Violation",
        catTone: "bad",
        title: "Work Cell",
        timeLabel: "5:52 AM",
        body: "Floor fans and an air mover obstructing the designated aisle, while the safety glasses compartment is empty and requires restocking.",
        risk: "Medium Risk",
        riskTone: "warn",
        status: "In Progress",
        stTone: "warn",
      },
      {
        category: "Violation",
        catTone: "bad",
        title: "Main Aisle",
        timeLabel: "5:41 AM",
        body: "S&R cart and wire racks extending over the marked aisle line, reducing safe clearance and restricting passage.",
        risk: "High Risk",
        riskTone: "bad",
        status: "In Progress",
        stTone: "warn",
      },
      {
        category: "Violation",
        catTone: "warn",
        title: "Work Cell",
        timeLabel: "5:35 AM",
        body: "Eyewash saline bottle is present and properly stocked, while the safety glasses compartment is empty and requires restocking.",
        risk: "Low Risk",
        riskTone: "good",
        status: "Open",
        stTone: "bad",
      },
      {
        category: "Violation",
        catTone: "warn",
        title: "Production Area",
        timeLabel: "5:22 AM",
        body: "Office chair obstructing the designated aisle, with loose wires on the floor creating a trip hazard and reducing safe clearance.",
        risk: "Low Risk",
        riskTone: "good",
        status: "Open",
        stTone: "bad",
      },
    ],

    trends: {
      obs: { arrow: "up", pct: 20, isGood: true },
      viol: { arrow: "up", pct: 12, isGood: false },
      open: { arrow: "up", pct: 8, isGood: false },
    },
  },
};

export const HARLAND_SECURITY_DATA = {
  125: {
    scorePct: 94,
    scoreWord: "Excellent",
    totalEvents: 13,
    highSev: 1,
    medSev: 4,
    lowSev: 8,
    openInvestigations: 2,
    cameraOnline: 49,
    cameraTotal: 50,
    lead: "Robert Lin",
    imageOffset: 0,
    locations: [
      "BU125 Back Entrance",
      "BU125 North Perimeter",
      "Coater Loading Door",
      "BU125 Server Corridor",
      "BU125 Reception",
    ],
  },

  120: {
    scorePct: 88,
    scoreWord: "Good",
    totalEvents: 18,
    highSev: 2,
    medSev: 5,
    lowSev: 11,
    openInvestigations: 3,
    cameraOnline: 47,
    cameraTotal: 50,
    lead: "Aisha Mensah",
    imageOffset: 1,
    locations: [
      "BU120 Employee Entrance",
      "RDX Perimeter",
      "Material Loading Door",
      "Control Room Corridor",
      "BU120 Visitor Desk",
    ],
  },

  140: {
    scorePct: 84,
    scoreWord: "Good",
    totalEvents: 21,
    highSev: 2,
    medSev: 6,
    lowSev: 13,
    openInvestigations: 4,
    cameraOnline: 44,
    cameraTotal: 50,
    lead: "Diego Vela",
    imageOffset: 2,
    locations: [
      "BU140 South Entrance",
      "Production Fence",
      "Packaging Door",
      "Electrical Room Corridor",
      "BU140 Lobby",
    ],
  },

  150: {
    scorePct: 96,
    scoreWord: "Excellent",
    totalEvents: 12,
    highSev: 0,
    medSev: 3,
    lowSev: 9,
    openInvestigations: 1,
    cameraOnline: 50,
    cameraTotal: 50,
    lead: "Hannah O’Brien",
    imageOffset: 3,
    locations: [
      "Final Assembly Entrance",
      "Finished Goods Perimeter",
      "Shipping Door",
      "Quality Corridor",
      "BU150 Reception",
    ],
  },

  180: {
    scorePct: 90,
    scoreWord: "Good",
    totalEvents: 17,
    highSev: 1,
    medSev: 5,
    lowSev: 11,
    openInvestigations: 3,
    cameraOnline: 46,
    cameraTotal: 49,
    lead: "Ren Tanaka",
    imageOffset: 4,
    locations: [
      "Coating Area Entrance",
      "Chemical Store Perimeter",
      "Curing Dock Door",
      "Utility Corridor",
      "BU180 Check-In",
    ],
  },

  190: {
    scorePct: 92,
    scoreWord: "Excellent",
    totalEvents: 14,
    highSev: 1,
    medSev: 4,
    lowSev: 9,
    openInvestigations: 2,
    cameraOnline: 48,
    cameraTotal: 50,
    lead: "Lila Petrov",
    imageOffset: 0,
    locations: [
      "Kitting Entrance",
      "Sub-Assembly Perimeter",
      "Component Receiving Door",
      "Tool Room Corridor",
      "BU190 Visitor Desk",
    ],
  },

  220: {
    scorePct: 97,
    scoreWord: "Excellent",
    totalEvents: 9,
    highSev: 0,
    medSev: 2,
    lowSev: 7,
    openInvestigations: 1,
    cameraOnline: 51,
    cameraTotal: 52,
    lead: "Robert Lin",
    imageOffset: 1,
    locations: [
      "Quality Lab Entrance",
      "Test Bay Perimeter",
      "Sample Storage Door",
      "Calibration Corridor",
      "BU220 Reception",
    ],
  },

  warehouse: {
    scorePct: 82,
    scoreWord: "Watch",
    totalEvents: 26,
    highSev: 3,
    medSev: 8,
    lowSev: 15,
    openInvestigations: 5,
    cameraOnline: 56,
    cameraTotal: 60,
    lead: "Aisha Mensah",
    imageOffset: 2,
    locations: [
      "Inbound Vehicle Gate",
      "Warehouse North Perimeter",
      "Loading Dock 4",
      "Inventory Cage Corridor",
      "Driver Check-In",
    ],
  },
};

export const HARLAND_SYSTEMS_DATA = {
  125: {
    heading: "Systems — BU125 Coating and Test Equipment",
    metrics: [
      { label: "Active Machines", value: "9 / 10", hint: "1 machine offline" },
      { label: "Throughput", value: "106/hr", hint: "+4% vs yesterday" },
      { label: "Cycle Time", value: "42 sec", hint: "Target: 45 sec" },
      { label: "Open Alerts", value: "2", hint: "1 requires attention" },
    ],
  },

  120: {
    heading: "Systems — BU120 Commercialization Equipment",
    metrics: [
      { label: "Active Machines", value: "7 / 10", hint: "3 under review" },
      { label: "Throughput", value: "92/hr", hint: "-3% vs target" },
      { label: "Cycle Time", value: "48 sec", hint: "Target: 46 sec" },
      { label: "Open Alerts", value: "4", hint: "2 require attention" },
    ],
  },

  140: {
    heading: "Systems — BU140 Production Equipment",
    metrics: [
      { label: "Active Machines", value: "6 / 10", hint: "4 unavailable" },
      { label: "Throughput", value: "84/hr", hint: "-8% vs target" },
      { label: "Cycle Time", value: "51 sec", hint: "Target: 45 sec" },
      { label: "Open Alerts", value: "6", hint: "2 critical alerts" },
    ],
  },

  150: {
    heading: "Systems — BU150 Final Assembly",
    metrics: [
      { label: "Active Machines", value: "7 / 8", hint: "1 planned stop" },
      { label: "Throughput", value: "101/hr", hint: "+2% vs target" },
      { label: "Cycle Time", value: "44 sec", hint: "Within target" },
      { label: "Open Alerts", value: "1", hint: "Low severity" },
    ],
  },

  180: {
    heading: "Systems — BU180 Coating and Curing",
    metrics: [
      { label: "Active Machines", value: "6 / 8", hint: "2 in maintenance" },
      { label: "Throughput", value: "82/hr", hint: "-5% vs target" },
      { label: "Cycle Time", value: "53 sec", hint: "Target: 49 sec" },
      { label: "Open Alerts", value: "3", hint: "Temperature variance" },
    ],
  },

  190: {
    heading: "Systems — BU190 Sub-Assembly and Kitting",
    metrics: [
      { label: "Active Machines", value: "8 / 9", hint: "1 machine idle" },
      { label: "Throughput", value: "98/hr", hint: "+1% vs target" },
      { label: "Cycle Time", value: "46 sec", hint: "Within target" },
      { label: "Open Alerts", value: "2", hint: "Material flow alerts" },
    ],
  },

  220: {
    heading: "Systems — BU220 Quality Laboratory",
    metrics: [
      { label: "Active Machines", value: "5 / 6", hint: "1 calibrating" },
      { label: "Test Throughput", value: "94/hr", hint: "+6% vs target" },
      { label: "Test Cycle", value: "38 sec", hint: "Target: 40 sec" },
      { label: "Open Alerts", value: "1", hint: "Calibration reminder" },
    ],
  },

  warehouse: {
    heading: "Systems — Warehouse and Logistics",
    metrics: [
      { label: "Dock Availability", value: "7 / 8", hint: "1 dock occupied" },
      { label: "Pallet Movement", value: "168/hr", hint: "+9% vs yesterday" },
      { label: "Inventory Accuracy", value: "99.2%", hint: "Target: 99%" },
      { label: "Open Alerts", value: "5", hint: "2 forklift alerts" },
    ],
  },
};
