/** Demo property drill-downs for Aviora Construction — copy aligned to stakeholder decks PR 101–103. */

import siteSkyline from '../assets/uploads/aviora-site-skyline-residences.jpg'
import siteGreenfield from '../assets/uploads/aviora-site-greenfield-heights.jpg'
import siteRiverstone from '../assets/uploads/aviora-site-riverstone-villas.jpg'
import { AVIORA_OLIVIA_LEAD_IMAGE_URL } from './avioraPortfolioData.js'
import leadEthan from '../assets/uploads/aviora-lead-ethan-brooks.jpg'
import leadMaya from '../assets/uploads/aviora-lead-maya-singh.jpg'

export const AVIORA_PROPERTY_DETAIL_IDS = ['skyline', 'greenfield', 'riverstone']

/** @param {string} id */
export function isAvioraPropertyDetailId(id) {
  return AVIORA_PROPERTY_DETAIL_IDS.includes(id)
}

export const AVIORA_PROPERTY_DETAILS = {
  skyline: {
    id: 'skyline',
    code: 'PR 101',
    name: 'Skyline Residences',
    heroImage: siteSkyline,
    description: '18-floor urban residential tower',
    portfolioTone: 'operational',
    currentStatusLabel: 'Running',
    projectManager: { name: 'Olivia Carter', photo: AVIORA_OLIVIA_LEAD_IMAGE_URL, photoFocus: '50% 38%' },
    siteEngineer: { name: 'Daniel Perez', photo: null },
    realtime: [
      { label: 'Active Crews', value: '9' },
      { label: 'On-Track Packages', value: '4' },
      { label: 'At Risk Packages', value: '1' },
      { label: 'Delayed Packages', value: '1' },
      { label: 'Day', value: '72 of 120' },
    ],
    construction: [
      { label: 'Overall Completion', value: '62%' },
      { label: 'Avg Daily Progress', value: '0.84%' },
      { label: 'Safety Score', value: '91%' },
      { label: 'Quality Score', value: '88%' },
      { label: 'Open Issues', value: '14' },
    ],
    deliveryBullets: [
      { tone: 'ok', text: 'On Track: 3' },
      { tone: 'warn', text: 'At Risk: 2' },
      { tone: 'bad', text: 'Delayed: 1' },
    ],
    deliveryFoot: 'Forecast completion: on watch.',
    snapshot: {
      kind: 'skyline',
      crewsActive: 9,
      crewsTotal: 14,
      completionPct: 62,
      completionSub: 'Avg days 20',
      scheduleAhead: 2,
      scheduleOnTime: 2,
      scheduleBehind: 2,
      deliveryOnTrack: 3,
      deliveryAtRisk: 2,
      deliveryDelayed: 1,
    },
    packages: [
      {
        num: 1,
        title: 'Tower A',
        subtitle: 'High-rise residential',
        status: 'onTrack',
        pct: 78,
        timeVariance: '+2 days Ahead',
        daysLeft: 12,
        image: siteSkyline,
        imageFocus: '50% 32%',
      },
      {
        num: 2,
        title: 'Tower B',
        subtitle: 'High-rise residential',
        status: 'atRisk',
        pct: 66,
        timeVariance: '−2 days Behind',
        daysLeft: 18,
        image: siteSkyline,
        imageFocus: '82% 40%',
      },
      {
        num: 3,
        title: 'Facade & glazing',
        subtitle: 'Envelope',
        status: 'onTrack',
        pct: 59,
        timeVariance: '0 days On time',
        daysLeft: 20,
        image: siteSkyline,
        imageFocus: '28% 55%',
      },
      {
        num: 4,
        title: 'Parking podium',
        subtitle: 'Structure',
        status: 'onTrack',
        pct: 72,
        timeVariance: '+1 day Ahead',
        daysLeft: 15,
        image: siteGreenfield,
        imageFocus: '55% 45%',
      },
      {
        num: 5,
        title: 'Clubhouse lobby',
        subtitle: 'Interiors',
        status: 'atRisk',
        pct: 45,
        timeVariance: '−3 days Behind',
        daysLeft: 27,
        image: siteRiverstone,
        imageFocus: '48% 42%',
      },
      {
        num: 6,
        title: 'Landscaping',
        subtitle: 'Site works',
        status: 'delayed',
        pct: 33,
        timeVariance: '−5 days Behind',
        daysLeft: 31,
        image: siteRiverstone,
        imageFocus: '50% 88%',
      },
    ],
  },
  greenfield: {
    id: 'greenfield',
    code: 'PR 102',
    name: 'Greenfield Heights',
    heroImage: siteGreenfield,
    description: 'Mid-rise apartment community',
    portfolioTone: 'monitoring',
    currentStatusLabel: 'Monitoring',
    projectManager: { name: 'Ethan Brooks', photo: leadEthan, photoFocus: '50% 18%' },
    siteEngineer: { name: 'Sophia Reed', photo: null },
    realtime: [
      { label: 'Active Crews', value: '8' },
      { label: 'On-Track Packages', value: '3' },
      { label: 'At Risk Packages', value: '2' },
      { label: 'Delayed Packages', value: '1' },
      { label: 'Day', value: '58 of 120' },
    ],
    construction: [
      { label: 'Overall Completion', value: '48%' },
      { label: 'Target vs Actual', value: '52% vs 49%' },
      { label: 'Cycle Time', value: 'Steady' },
      { label: 'Safety Score', value: '87%' },
      { label: 'Quality Score', value: '86%' },
      { label: 'Open Issues', value: '9' },
    ],
    deliveryBullets: [
      { tone: 'ok', text: 'On Track: 3' },
      { tone: 'warn', text: 'At Risk: 2' },
      { tone: 'bad', text: 'Delayed: 1' },
    ],
    deliveryFoot: 'Forecast completion: monitoring.',
    snapshot: {
      kind: 'greenfield',
      crewsActive: 8,
      targetPct: 52,
      actualPct: 49,
      linePoints: [42, 44, 41, 46, 48, 47, 49],
      throughputBars: [62, 78, 55, 70],
    },
    packages: [
      {
        num: 1,
        title: 'Block A',
        subtitle: 'Mid-rise residential',
        status: 'onTrack',
        pct: 71,
        timeVariance: '+1 day Ahead',
        daysLeft: 14,
        image: siteGreenfield,
        imageFocus: '45% 40%',
      },
      {
        num: 2,
        title: 'Block B',
        subtitle: 'Mid-rise residential',
        status: 'onTrack',
        pct: 69,
        timeVariance: '+2 days Ahead',
        daysLeft: 12,
        image: siteGreenfield,
        imageFocus: '70% 48%',
      },
      {
        num: 3,
        title: 'Pool & clubhouse',
        subtitle: 'Amenity core',
        status: 'atRisk',
        pct: 42,
        timeVariance: '−1 day Behind',
        daysLeft: 24,
        image: siteRiverstone,
        imageFocus: '52% 55%',
      },
      {
        num: 4,
        title: 'Internal roads',
        subtitle: 'Civil',
        status: 'delayed',
        pct: 36,
        timeVariance: '−4 days Behind',
        daysLeft: 28,
        image: siteSkyline,
        imageFocus: '50% 70%',
      },
      {
        num: 5,
        title: 'Utilities',
        subtitle: 'Site infrastructure',
        status: 'onTrack',
        pct: 55,
        timeVariance: '0 days On time',
        daysLeft: 19,
        image: siteGreenfield,
        imageFocus: '30% 60%',
      },
      {
        num: 6,
        title: 'Landscaping',
        subtitle: 'Exterior',
        status: 'atRisk',
        pct: 22,
        timeVariance: '−3 days Behind',
        daysLeft: 34,
        image: siteRiverstone,
        imageFocus: '55% 90%',
      },
    ],
  },
  riverstone: {
    id: 'riverstone',
    code: 'PR 103',
    name: 'Riverstone Villas',
    heroImage: siteRiverstone,
    description: 'Gated villa development',
    portfolioTone: 'risk',
    currentStatusLabel: 'Recovery',
    projectManager: { name: 'Maya Singh', photo: leadMaya, photoFocus: '50% 16%' },
    siteEngineer: { name: 'Ryan Patel', photo: null },
    realtime: [
      { label: 'Active Crews', value: '7' },
      { label: 'On-Track Packages', value: '2' },
      { label: 'At Risk Packages', value: '2' },
      { label: 'Delayed Packages', value: '2' },
      { label: 'Day', value: '39 of 120' },
    ],
    construction: [
      { label: 'Overall Completion', value: '38%' },
      { label: 'Avg Days Remaining', value: '29' },
      { label: 'Avg Completion Rate', value: '0.8%/day' },
      { label: 'Quality Score', value: '87%' },
      { label: 'Open Issues', value: '18' },
    ],
    deliveryBullets: [
      { tone: 'ok', text: 'On Track: 2' },
      { tone: 'warn', text: 'At Risk: 2' },
      { tone: 'bad', text: 'Delayed: 2' },
    ],
    deliveryFoot: 'Forecast completion: on track.',
    snapshot: {
      kind: 'riverstone',
      crewsActive: 7,
      crewsDelta: '+1 vs yesterday',
      completionPct: 33,
      completionDelta: '+1% vs yesterday',
      scheduleAhead: 1,
      scheduleOnTime: 1,
      scheduleBehind: 4,
      deliveryOnTrack: 2,
      deliveryAtRisk: 2,
      deliveryDelayed: 2,
    },
    packages: [
      {
        num: 1,
        title: 'Villa cluster A',
        subtitle: 'Residential',
        status: 'onTrack',
        pct: 48,
        timeVariance: '+1 day Ahead',
        daysLeft: 22,
        image: siteRiverstone,
        imageFocus: '40% 45%',
      },
      {
        num: 2,
        title: 'Villa cluster B',
        subtitle: 'Residential',
        status: 'atRisk',
        pct: 41,
        timeVariance: '−2 days Behind',
        daysLeft: 25,
        image: siteRiverstone,
        imageFocus: '75% 50%',
      },
      {
        num: 3,
        title: 'Clubhouse',
        subtitle: 'Amenity',
        status: 'delayed',
        pct: 27,
        timeVariance: '−5 days Behind',
        daysLeft: 36,
        image: siteGreenfield,
        imageFocus: '50% 42%',
      },
      {
        num: 4,
        title: 'Site utilities',
        subtitle: 'Underground',
        status: 'atRisk',
        pct: 38,
        timeVariance: '−3 days Behind',
        daysLeft: 30,
        image: siteSkyline,
        imageFocus: '55% 65%',
      },
      {
        num: 5,
        title: 'Roofing & exterior',
        subtitle: 'Envelope',
        status: 'delayed',
        pct: 24,
        timeVariance: '−5 days Behind',
        daysLeft: 38,
        image: siteGreenfield,
        imageFocus: '60% 35%',
      },
      {
        num: 6,
        title: 'Boundary & landscape',
        subtitle: 'Perimeter',
        status: 'delayed',
        pct: 18,
        timeVariance: '−7 days Behind',
        daysLeft: 42,
        image: siteRiverstone,
        imageFocus: '50% 92%',
      },
    ],
  },
}
